**Wesleyan University ASTR 210**

# Exercise 3

## Import statement

Always put your import statements at the top!  Import the numpy package below, renaming it as np.

In [25]:
import numpy as np # YOUR CODE HERE

## Initializing arrays

There are often multiple equivalent ways to create a given array.  Below, you will create arrays arr1 and arr2 using three different methods each.

Create an array called arr1 whose contents are [2, 5, 8, 11, 14, 17, 20] by 

(i) using np.array() to convert a list

In [4]:
arr1 = arr1 = np.array([2, 5, 8, 11, 14, 17, 20])# YOUR CODE HERE
arr1# YOUR CODE HERE


array([ 2,  5,  8, 11, 14, 17, 20])

(ii) using np.arange() and arithmetic

In [5]:
arr1 =np.arange(1, 21, 3) + 1 # YOUR CODE HERE
arr1

array([ 2,  5,  8, 11, 14, 17, 20])

(iii) using np.linspace()

In [6]:
arr1 = np.linspace(2, 20, 7)# YOUR CODE HERE
arr1

array([ 2.,  5.,  8., 11., 14., 17., 20.])

Create an array named arr2 which is the same length as arr1, whose elements all have the value 2, by

(i) using np.array() to convert a list

In [7]:
arr2 = np.array([2] * len(arr1)) # YOUR CODE HERE
arr2

array([2, 2, 2, 2, 2, 2, 2])

(ii) using np.zeros() and addition

In [8]:
arr2 = np.zeros(len(arr1)) + 2 # YOUR CODE HERE
arr2

array([2., 2., 2., 2., 2., 2., 2.])

(iii) using np.ones() and multiplication

In [9]:
arr2 = np.ones(len(arr1)) * 2 # YOUR CODE HERE
arr2

array([2., 2., 2., 2., 2., 2., 2.])

## Combining arrays

In the cells below, calculate and print:

The sum of arr1 and arr2:

In [10]:
arr1 + arr2 # YOUR CODE HERE

array([ 4.,  7., 10., 13., 16., 19., 22.])

The product of arr1 and arr2:

In [11]:
arr1 * arr2 # YOUR CODE HERE

array([ 4., 10., 16., 22., 28., 34., 40.])

The square of arr1:

In [12]:
arr1**2 # YOUR CODE HERE

array([  4.,  25.,  64., 121., 196., 289., 400.])

## Indexing arrays

Print the first four elements of arr1:

In [13]:
arr1[0:4]# YOUR CODE HERE

array([ 2.,  5.,  8., 11.])

Print the last four elements of arr1:

In [14]:
arr1[-4:]# YOUR CODE HERE

array([11., 14., 17., 20.])

Define a Boolean array doubledigits which is True where arr1 is at least 10, and False otherwise:

In [15]:
doubledigits = arr1 > 9 # YOUR CODE HERE
print(arr1)
print(doubledigits)

[ 2.  5.  8. 11. 14. 17. 20.]
[False False False  True  True  True  True]


Use doubledigits to print out the elements of arr1 which are at least 10:

In [16]:
print(arr1[doubledigits]) # YOUR CODE HERE

[11. 14. 17. 20.]


Use doubledigits to print out the elements of arr1 which are *less than* 10:

In [17]:
print(arr1[~doubledigits]) # YOUR CODE HERE

[2. 5. 8.]


## Array math and functions

In the cell below, I import a module named "math" which knows the value of $\pi$ (as in, $A_{\rm circle}=\pi r^2$) to high precision, and assign that value to a variable named "pi".

In [24]:
import math
pi = math.pi
print(pi)

3.141592653589793


Use the np.linspace() function to create an array named theta that ranges from 0 to $2\pi$ with 9 elements:

In [19]:
theta = np.linspace(0, 2*pi, 9) # YOUR CODE HERE
print(theta)

[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]


If you initialized it correctly, theta should be $[0,\frac{\pi}{4},\frac{\pi}{2},\frac{3\pi}{4},\pi,\frac{5\pi}{4},\frac{6\pi}{4},\frac{7\pi}{4},2\pi]$.  Check your work by printing out theta normalized (i.e., divided) by $\pi$.

In [20]:
print(theta/pi) # YOUR CODE HERE# YOUR CODE HERE

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


The numpy package includes many useful mathematical functions (see the cheat sheet on the Moodle), including all the trigonometric functions like sine and cosine.  Our array theta, if interpreted as a set of angles in units of radians, goes all the way around the unit circle.  Use the np.sin() and np.cos() functions to print out the sine and cosine of each element of theta.

In [21]:
print(np.sin(theta)) # YOUR CODE HERE (sine)
print(np.cos(theta)) # YOUR CODE HERE (cosine)

[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00 -7.07106781e-01 -1.83697020e-16  7.07106781e-01
  1.00000000e+00]


The values you printed out likely went out to a lot of decimal places and were printed out using scientific notation, i.e., $x$ e $y = x \times 10^y$.  Moreover, you may notice that some elements of the array are very very small, something $\times 10^{-16}$!  This is because of finite *machine precision*.  Computers can only store a finite number of decimal places, but $\pi$ is an irrational number with an infinite number of decimal places.  So, when we perform calculations using $\pi$, we cannot help but introduce a small amount of error because we had to round it.  If you look at the values of theta where those $10^{-16}$'s are generated, you will see that those are elements where $\sin(\theta)$ or $\cos(\theta)$ should be *zero*.

We can make these arrays a little bit more human-readable by rounding the numbers to a smaller number of decimal places.  The np.around() function will do just that.  It takes as the first argument the array you would like to round, then an *optional argument* called decimals which determines how many decimal places to round to.  (We will talk more about optional arguments later on.)  I have written a call to np.around() below which will round X to three decimal places.  Replace X with your code for $\sin(\theta)$ and $\cos(\theta)$.

In [22]:
print(np.around(np.sin(theta), decimals=3)) # Replace X with your code for sine of theta
print(np.around(np.cos(theta), decimals=3)) # Replace X with your code for cosine of theta

[ 0.     0.707  1.     0.707  0.    -0.707 -1.    -0.707 -0.   ]
[ 1.     0.707  0.    -0.707 -1.    -0.707 -0.     0.707  1.   ]


In case you were wondering:

In [23]:
np.sqrt(2)/2

np.float64(0.7071067811865476)